export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SUCCESS_AUTHORIZATION_USER = 'SUCCESS_LOGIN_USER';
export const SEND_TOKEN_TO_REFRESH = 'SEND_TOKEN_TO_REFRESH';
export const SUCCESS_REFRESH_TOKEN = 'SUCCESS_REFRESH_TOKEN';
export const LOG_OUT_USER = 'LOG_OUT_USER';